### ISSUE TITLE
Google_Client class not found.

### ISSUE THREAD

**Issue by SalocinDotTEN** [wintercms/wn-googleanalytics-plugin#2]
Upon loading the Winter CMS Dashboard, the following appears and the dashboard goes into infinite loading...

"Class "Google_Client" not found" on line 42 of /.../public_html/plugins/winter/googleanalytics/classes/Analytics.php

**Comment by LukeTowers** [comment]
What did you use to install the plugin?

**Comment by SalocinDotTEN** [comment]
Thanks @LukeTowers .

Used the command line to install the plugin. The php artisan plugin:install command line.

**Comment by AIC-BV** [comment]
I'm having the same issue, also installed with php artisan plugin:install Winter.GoogleAnalytics

**Comment by AIC-BV** [comment]
You have to add it in composer using the following code
`composer require google/apiclient`

**Comment by LukeTowers** [comment]
You can also just install the plugin with `composer require winter/wn-googleanalytics-plugin` and it should work without anything else.
